export const KEY_ACTION_GET = {
    GET_USER :"GET_USER",
    GET_CART_PRODUCT:"GET_CART_PRODUCT"
}

export const KEY_ACTION_SET = {
    SET_USER :"SET_USER",
    SET_CART_PRODUCT:"SET_CART_PRODUCT"
}

export const KEY_ACTION_CLEAR = {
    CLEAR_USER :"CLEAR_USER",
    CLEAR_CART_PRODUCT:"CLEAR_CART_PRODUCT"
}